import { defineConfig } from 'wxt';

// See https://wxt.dev/api/config.html
export default defineConfig({
  modules: ['@wxt-dev/module-react'],
  manifest: {
    name: 'Dagobang 打狗棒',
    description: 'Trubo Open-source Meme Trading Tool',
    version: '0.4.0',
    permissions: ['storage', 'alarms', 'sidePanel'],
    host_permissions: [
      'https://*.gmgn.ai/*',
      'https://gmgn.ai/*',
      'https://*.axiom.trade/*',
      'https://axiom.trade/*',
      'https://*.four.meme/*',
      'https://four.meme/*',
      'https://*.alt.fun/*',
      'https://alt.fun/*',
      'https://*.ponsfamily.com/*',
      'https://ponsfamily.com/*',
      'https://*.pons.fun/*',
      'https://pons.fun/*',
      'https://*.flap.sh/*',
      'https://flap.sh/*',
      'https://web3.binance.com/*',
      'https://web3.okx.com/*',
      'https://*.dexscreener.com/*',
      'https://dexscreener.com/*',
      'https://*.xxyy.io/*',
      'https://xxyy.io/*',
      'https://*.debot.ai/*',
      'https://debot.ai/*',
      'https://api.blxrbdn.com/*',
      'https://bsc.rpc.blxrbdn.com/*',
      'https://*.blxrbdn.com/*',
      'https://*.supabase.co/*',
      'https://www.google.com/*',
      'https://*/*',
    ],
    web_accessible_resources: [
      {
        resources: ['sounds/*.mp3'],
        matches: [
          '*://axiom.trade/*',
          '*://*.axiom.trade/*',
          '*://debot.ai/*',
          '*://*.debot.ai/*',
          '*://dexscreener.com/*',
          '*://*.dexscreener.com/*',
          '*://flap.sh/*',
          '*://*.flap.sh/*',
          '*://four.meme/*',
          '*://*.four.meme/*',
          '*://alt.fun/*',
          '*://*.alt.fun/*',
          '*://ponsfamily.com/*',
          '*://*.ponsfamily.com/*',
          '*://pons.fun/*',
          '*://*.pons.fun/*',
          '*://gmgn.ai/*',
          '*://*.gmgn.ai/*',
          '*://web3.binance.com/*',
          '*://web3.okx.com/*',
          '*://xxyy.io/*',
          '*://*.xxyy.io/*',
        ],
      },
    ],
    action: {
      default_title: 'Dagobang 打狗棒',
    },
    side_panel: {
      default_path: 'sidepanel.html',
    },
  },
});
