export enum ContractNames {
  DagobangRouter = "DagobangRouter",
  WETH = "WETH",
  UniswapFactoryV2 = "UniswapFactoryV2",
  PancakeFactoryV2 = "PancakeFactoryV2",
  UniswapFactoryV3 = "UniswapFactoryV3",
  PancakeFactoryV3 = "PancakeFactoryV3",
  PoolManager = "PoolManager",
  PancakeInfinityVault = "PancakeInfinityVault",
  PancakeInfinityClPoolManager = "PancakeInfinityClPoolManager",
  PancakeInfinityBinPoolManager = "PancakeInfinityBinPoolManager",
  FourMemeTokenManagerV2 = "FourMemeTokenManagerV2",
  FlapshTokenManager = "FlapshTokenManager",
  TokenManagerHelper3 = "TokenManagerHelper3",
  HyperZap = "HyperZap",
  HyperBonding = "HyperBonding",
  PonsV1Factory = "PonsV1Factory",
  PonsV1LegacyFactory = "PonsV1LegacyFactory",
  PonsV2Factory = "PonsV2Factory",
  PonsMemeHook = "PonsMemeHook",
  GeniusLaunchFactory = "GeniusLaunchFactory",
  GeniusMemeHook = "GeniusMemeHook",
}
