import type { Settings, ChainSettings, AutoTradeConfig, GasGweiConfig, AdvancedAutoSellConfig } from '../types/extention';
import { ChainId } from '@/constants/chains';

const DEFAULT_GAS_GWEI: GasGweiConfig = {
  slow: '0.06',
  standard: '0.12',
  fast: '1',
  turbo: '5',
};

const DEFAULT_PRIORITY_FEE_PRESETS = {
  none: '0',
  slow: '0.000025',
  standard: '0.00004',
  fast: '0.0001',
} as const;

export const DEFAULT_SOLANA_TIP_PRESET_VALUES = {
  none: '0',
  slow: '0.001',
  standard: '0.002',
  fast: '0.005',
} as const;

const DEFAULT_QUICK_BUY_PRESET_OVERRIDES = [{}, {}, {}, {}];

const BSC_MAINNET: ChainSettings = {
  rpcUrls: [
    'https://0.48.club',
    'https://1rpc.io/bnb',
    'https://bsc.rpc.blxrbdn.com',
    'https://bsc-dataseed.ninicoin.io',
    'https://bsc-dataseed.defibit.io',
    'https://bsc-dataseed-public.bnbchain.org',
    'https://bscrpc.pancakeswap.finance',
  ],
  protectedRpcUrls: [
    'https://bscrpc.pancakeswap.finance',
    'https://pancake.rpc.48.club',
    'https://four.rpc.48.club',
    'https://debot.bsc.blockrazor.xyz'
  ],
  protectedRpcUrlsBuy: [
  ],
  protectedRpcUrlsSell: [
  ],
  submitChannel: 'blockrazor',
  tradeBaseToken: 'BNB',
  antiMev: true,
  gasPreset: 'standard',
  buyGasPreset: 'standard',
  sellGasPreset: 'standard',
  executionMode: 'default',
  gasPriceMode: 'fixed',
  slippageBps: 4000,
  deadlineSeconds: 60,
  buyPresets: ['0.05', '0.1', '0.5', '1'],
  sellPresets: ['10', '20', '50', '100'],
  buyGasGwei: DEFAULT_GAS_GWEI,
  sellGasGwei: DEFAULT_GAS_GWEI,
  approveGasGwei: '0.06',
  buyPriorityFeePreset: 'standard',
  sellPriorityFeePreset: 'standard',
  buyPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  sellPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  buyTipPreset: 'none',
  sellTipPreset: 'none',
  buyTipPresets: DEFAULT_SOLANA_TIP_PRESET_VALUES,
  sellTipPresets: DEFAULT_SOLANA_TIP_PRESET_VALUES,
  quickBuyAdvancedEnabled: false,
  quickBuyPresetOverrides: DEFAULT_QUICK_BUY_PRESET_OVERRIDES,
  bloxrouteBuyEnabled: true,
  bloxrouteSellEnabled: true,
};

const ETH_GAS_GWEI: GasGweiConfig = {
  slow: '1',
  standard: '2',
  fast: '5',
  turbo: '15',
};

const ETH_MAINNET: ChainSettings = {
  rpcUrls: [
    'https://eth.llamarpc.com',
    'https://ethereum.publicnode.com',
    'https://rpc.ankr.com/eth',
  ],
  protectedRpcUrls: [],
  protectedRpcUrlsBuy: [],
  protectedRpcUrlsSell: [],
  submitChannel: 'protectRpcs',
  tradeBaseToken: 'BNB',
  antiMev: false,
  gasPreset: 'standard',
  buyGasPreset: 'standard',
  sellGasPreset: 'standard',
  executionMode: 'default',
  gasPriceMode: 'dynamic',
  slippageBps: 4000,
  deadlineSeconds: 60,
  buyPresets: ['0.01', '0.05', '0.1', '0.2'],
  sellPresets: ['10', '20', '50', '100'],
  buyGasGwei: ETH_GAS_GWEI,
  sellGasGwei: ETH_GAS_GWEI,
  approveGasGwei: '2',
  buyPriorityFeePreset: 'standard',
  sellPriorityFeePreset: 'standard',
  buyPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  sellPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  quickBuyAdvancedEnabled: false,
  quickBuyPresetOverrides: DEFAULT_QUICK_BUY_PRESET_OVERRIDES,
  bloxrouteBuyEnabled: true,
  bloxrouteSellEnabled: true,
};

const HYPER_GAS_GWEI: GasGweiConfig = {
  slow: '0.4',
  standard: '0.6',
  fast: '1',
  turbo: '3',
};

const HYPER_MAINNET: ChainSettings = {
  rpcUrls: [
    'https://rpc.hyperliquid.xyz/evm',
    'https://rpc.hyperlend.finance',
    'https://rpc.hypurrscan.io',
  ],
  protectedRpcUrls: ['https://hyperliquid.drpc.org',],
  protectedRpcUrlsBuy: [],
  protectedRpcUrlsSell: [],
  submitChannel: 'protectRpcs',
  tradeBaseToken: 'BNB',
  antiMev: false,
  gasPreset: 'standard',
  buyGasPreset: 'standard',
  sellGasPreset: 'standard',
  executionMode: 'default',
  gasPriceMode: 'dynamic',
  slippageBps: 4000,
  deadlineSeconds: 60,
  buyPresets: ['1', '2', '5', '10'],
  sellPresets: ['10', '20', '50', '100'],
  buyGasGwei: HYPER_GAS_GWEI,
  sellGasGwei: HYPER_GAS_GWEI,
  approveGasGwei: '0.6',
  buyPriorityFeePreset: 'standard',
  sellPriorityFeePreset: 'standard',
  buyPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  sellPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  quickBuyAdvancedEnabled: false,
  quickBuyPresetOverrides: DEFAULT_QUICK_BUY_PRESET_OVERRIDES,
  bloxrouteBuyEnabled: false,
  bloxrouteSellEnabled: false,
};

const RH_GAS_GWEI: GasGweiConfig = {
  slow: '0.001',
  standard: '0.01',
  fast: '0.05',
  turbo: '0.2',
};

const RH_MAINNET: ChainSettings = {
  rpcUrls: [
    'https://rpc.mainnet.chain.robinhood.com',
    'https://robinhood.rpc.blxrbdn.com',
    'https://rpc-robinhood.blockmachine.io',
    'https://rpc.ordofi.network',
  ],
  protectedRpcUrls: [
    'https://robinhood.api.pocket.network',
    'https://robinhood-rpc.publicnode.com',
    'https://robinhood.drpc.org',
  ],
  protectedRpcUrlsBuy: [],
  protectedRpcUrlsSell: [],
  submitChannel: 'protectRpcs',
  tradeBaseToken: 'BNB',
  antiMev: false,
  gasPreset: 'standard',
  buyGasPreset: 'standard',
  sellGasPreset: 'standard',
  executionMode: 'default',
  gasPriceMode: 'dynamic',
  slippageBps: 4000,
  deadlineSeconds: 60,
  buyPresets: ['0.01', '0.05', '0.1', '0.2'],
  sellPresets: ['10', '20', '50', '100'],
  buyGasGwei: RH_GAS_GWEI,
  sellGasGwei: RH_GAS_GWEI,
  approveGasGwei: '0.01',
  buyPriorityFeePreset: 'standard',
  sellPriorityFeePreset: 'standard',
  buyPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  sellPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  quickBuyAdvancedEnabled: false,
  quickBuyPresetOverrides: DEFAULT_QUICK_BUY_PRESET_OVERRIDES,
  bloxrouteBuyEnabled: false,
  bloxrouteSellEnabled: false,
};

const SOL_MAINNET: ChainSettings = {
  rpcUrls: [
    'https://public.rpc.solanavibestation.com',
    'https://solana.api.pocket.network',
  ],
  protectedRpcUrls: ['https://solana-rpc.publicnode.com'],
  protectedRpcUrlsBuy: [],
  protectedRpcUrlsSell: [],
  submitChannel: 'protectRpcs',
  tradeBaseToken: 'BNB',
  antiMev: false,
  gasPreset: 'standard',
  buyGasPreset: 'standard',
  sellGasPreset: 'standard',
  executionMode: 'default',
  gasPriceMode: 'dynamic',
  slippageBps: 4000,
  deadlineSeconds: 60,
  buyPresets: ['0.1', '0.5', '1', '2'],
  sellPresets: ['10', '20', '50', '100'],
  buyGasGwei: ETH_GAS_GWEI,
  sellGasGwei: ETH_GAS_GWEI,
  approveGasGwei: '0',
  buyPriorityFeePreset: 'standard',
  sellPriorityFeePreset: 'standard',
  buyPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  sellPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  quickBuyAdvancedEnabled: false,
  quickBuyPresetOverrides: DEFAULT_QUICK_BUY_PRESET_OVERRIDES,
  bloxrouteBuyEnabled: false,
  bloxrouteSellEnabled: false,
  solanaSwqos: {
    enabled: false,
    strategy: 'concurrent',
    timeoutMs: 10_000,
    region: 'default',
    providers: [
      { type: 'jito', enabled: false, weight: 70 },
      { type: 'blox', enabled: false, weight: 50 },
      { type: 'nextblock', enabled: false, weight: 30 },
      { type: 'temporal', enabled: false, weight: 20 },
      { type: 'zeroslot', enabled: false, weight: 20 },
      { type: 'node1', enabled: false, weight: 20 },
      { type: 'flashblock', enabled: false, weight: 20 },
      { type: 'blockrazor', enabled: false, weight: 20 },
      { type: 'astralane', enabled: false, weight: 20 },
    ],
  },
};

const DEFAULT_AUTOTRADE: AutoTradeConfig = {
  takeProfitMultiple: '2',
  stopLossMultiple: '0.5',
  maxHoldMinutes: '',
  wsMonitorEnabled: false,
  triggerSound: {
    enabled: true,
    preset: 'Boom',
  },
  twitterSnipe: {
    enabled: true,
    walletAddress: undefined,
    dryRun: true,
    dryRunBuyDelayMs: '1000',
    dryRunSellDelayMs: '2000',
    autoSellEnabled: true,
    buyAmountNative: '0.01',
    buyNewCaCount: '1',
    buyOgCount: '0',
    minMarketCapUsd: '',
    maxMarketCapUsd: '',
    minHolders: '',
    maxHolders: '',
    minKol: '',
    maxKol: '',
    minTickerLen: '',
    maxTickerLen: '',
    minTokenAgeSeconds: '',
    maxTokenAgeSeconds: '',
    minTweetAgeSeconds: '',
    maxTweetAgeSeconds: '',
    minDevHoldPercent: '',
    maxDevHoldPercent: '',
    minDevMaxBuyPercent: '',
    maxDevMaxBuyPercent: '',
    minViewerCount: '',
    maxViewerCount: '',
    minDevCreatedTokenCount: '',
    maxDevCreatedTokenCount: '',
    blockIfDevSell: true,
    wsConfirmEnabled: false,
    wsConfirmWindowMs: '5000',
    wsConfirmMinMcapChangePct: '5',
    wsConfirmMaxMcapChangePct: '120',
    wsConfirmMinHoldersDelta: '2',
    wsConfirmMinBuySellRatio: '1.6',
    wsConfirmMinNetBuy24hUsd: '3200',
    wsConfirmMinVol24hUsd: '9800',
    wsConfirmMinVolMcapRatio: '0.55',
    wsConfirmMinNetBuyMcapRatio: '0.19',
    wsConfirmMinSmartMoney: '0',
    rapidExitEnabled: true,
    rapidEvalStepSec: '4',
    rapidWatchdogSec: '1',
    rapidStopLossPct: '-20',
    rapidTakeProfitTriggerPct: '45',
    rapidTakeProfitStepUpPct: '25',
    rapidTakeProfitBatchPct: '15',
    rapidProtectQuotaPct: '40',
    rapidTailSellPctOfRemaining: '15',
    rapidTakeProfitFloorPct: '5',
    deleteTweetSellPercent: '',
    deleteTweetPlaySound: true,
    deleteTweetSoundPreset: 'Handgun',
    platforms: ['fourmeme', 'fourmeme_agent', 'xmode', 'xmode_agent', 'flap'],
    targetUsers: [],
    interactionTypes: ['tweet', 'reply', 'quote', 'retweet', 'follow'],
    presets: [
      {
        id: 'preset-flow',
        name: '流水盘',
        strategy: {
          enabled: true,
          walletAddress: undefined,
          dryRun: true,
          dryRunBuyDelayMs: '1000',
          dryRunSellDelayMs: '2000',
          autoSellEnabled: true,
          buyAmountNative: '0.006',
          buyNewCaCount: '1',
          buyOgCount: '0',
          minMarketCapUsd: '',
          maxMarketCapUsd: '800000',
          minHolders: '20',
          maxHolders: '',
          minKol: '',
          maxKol: '',
          minTickerLen: '',
          maxTickerLen: '',
          minTokenAgeSeconds: '',
          maxTokenAgeSeconds: '',
          minTweetAgeSeconds: '',
          maxTweetAgeSeconds: '240',
          minDevHoldPercent: '',
          maxDevHoldPercent: '20',
          minDevMaxBuyPercent: '',
          maxDevMaxBuyPercent: '',
          minViewerCount: '',
          maxViewerCount: '',
          minDevCreatedTokenCount: '',
          maxDevCreatedTokenCount: '',
          blockIfDevSell: true,
          wsConfirmEnabled: false,
          wsConfirmWindowMs: '5000',
          wsConfirmMinMcapChangePct: '5',
          wsConfirmMaxMcapChangePct: '120',
          wsConfirmMinHoldersDelta: '2',
          wsConfirmMinBuySellRatio: '2',
          wsConfirmMinNetBuy24hUsd: '3200',
          wsConfirmMinVol24hUsd: '9800',
          wsConfirmMinVolMcapRatio: '0.55',
          wsConfirmMinNetBuyMcapRatio: '0.19',
          wsConfirmMinSmartMoney: '0',
          rapidExitEnabled: true,
          rapidEvalStepSec: '5',
          rapidWatchdogSec: '1',
          rapidStopLossPct: '-20',
          rapidTakeProfitTriggerPct: '45',
          rapidTakeProfitStepUpPct: '25',
          rapidTakeProfitBatchPct: '15',
          rapidProtectQuotaPct: '40',
          rapidTailSellPctOfRemaining: '15',
          rapidTakeProfitFloorPct: '40',
          deleteTweetSellPercent: '',
          deleteTweetPlaySound: true,
          deleteTweetSoundPreset: 'Handgun',
          platforms: ['fourmeme', 'fourmeme_agent', 'xmode', 'xmode_agent', 'flap'],
          targetUsers: [],
          interactionTypes: ['tweet', 'reply', 'quote', 'retweet', 'follow'],
        },
      },
      {
        id: 'preset-trend',
        name: '趋势盘',
        strategy: {
          enabled: true,
          walletAddress: undefined,
          dryRun: true,
          dryRunBuyDelayMs: '1000',
          dryRunSellDelayMs: '2000',
          autoSellEnabled: true,
          buyAmountNative: '0.008',
          buyNewCaCount: '2',
          buyOgCount: '0',
          minMarketCapUsd: '120000',
          maxMarketCapUsd: '',
          minHolders: '40',
          maxHolders: '',
          minKol: '',
          maxKol: '',
          minTickerLen: '',
          maxTickerLen: '',
          minTokenAgeSeconds: '',
          maxTokenAgeSeconds: '',
          minTweetAgeSeconds: '',
          maxTweetAgeSeconds: '',
          minDevHoldPercent: '',
          maxDevHoldPercent: '35',
          minDevMaxBuyPercent: '',
          maxDevMaxBuyPercent: '',
          minViewerCount: '',
          maxViewerCount: '',
          minDevCreatedTokenCount: '',
          maxDevCreatedTokenCount: '',
          blockIfDevSell: true,
          wsConfirmEnabled: false,
          wsConfirmWindowMs: '5000',
          wsConfirmMinMcapChangePct: '5',
          wsConfirmMaxMcapChangePct: '120',
          wsConfirmMinHoldersDelta: '2',
          wsConfirmMinBuySellRatio: '1.6',
          wsConfirmMinNetBuy24hUsd: '3200',
          wsConfirmMinVol24hUsd: '9800',
          wsConfirmMinVolMcapRatio: '0.55',
          wsConfirmMinNetBuyMcapRatio: '0.19',
          wsConfirmMinSmartMoney: '0',
          rapidExitEnabled: true,
          rapidEvalStepSec: '5',
          rapidWatchdogSec: '1',
          rapidStopLossPct: '-20',
          rapidTakeProfitTriggerPct: '45',
          rapidTakeProfitStepUpPct: '25',
          rapidTakeProfitBatchPct: '15',
          rapidProtectQuotaPct: '40',
          rapidTailSellPctOfRemaining: '15',
          rapidTakeProfitFloorPct: '40',
          deleteTweetSellPercent: '',
          deleteTweetPlaySound: true,
          deleteTweetSoundPreset: 'Handgun',
          platforms: ['fourmeme', 'fourmeme_agent', 'xmode', 'xmode_agent', 'flap'],
          targetUsers: [],
          interactionTypes: ['tweet', 'reply', 'quote', 'retweet', 'follow'],
        },
      },
    ],
    activePresetId: 'preset-flow',
  },
  newCoinSnipe: {
    enabled: false,
    walletAddress: undefined,
    taskModeEnabled: true,
    dryRun: true,
    playSound: true,
    soundPreset: 'Boom',
    dryRunBuyDelayMs: '1000',
    dryRunSellDelayMs: '2000',
    autoSellEnabled: true,
    buyAmountNative: '0.006',
    buyGasGwei: '',
    buyBribeBnb: '',
    buyNewCaCount: '1',
    buyOgCount: '0',
    minMarketCapUsd: '',
    maxMarketCapUsd: '',
    minHolders: '',
    maxHolders: '',
    minKol: '',
    maxKol: '',
    minTickerLen: '',
    maxTickerLen: '',
    minTokenAgeSeconds: '',
    maxTokenAgeSeconds: '',
    minTweetAgeSeconds: '',
    maxTweetAgeSeconds: '',
    minDevHoldPercent: '',
    maxDevHoldPercent: '',
    minDevMaxBuyPercent: '',
    maxDevMaxBuyPercent: '',
    minViewerCount: '',
    maxViewerCount: '',
    minDevCreatedTokenCount: '',
    maxDevCreatedTokenCount: '',
    blockIfDevSell: true,
    wsConfirmEnabled: false,
    wsConfirmWindowMs: '5000',
    wsConfirmMinMcapChangePct: '5',
    wsConfirmMaxMcapChangePct: '120',
    wsConfirmMinHoldersDelta: '2',
    wsConfirmMinBuySellRatio: '1.6',
    wsConfirmMinNetBuy24hUsd: '3200',
    wsConfirmMinVol24hUsd: '9800',
    wsConfirmMinVolMcapRatio: '0.55',
    wsConfirmMinNetBuyMcapRatio: '0.19',
    wsConfirmMinSmartMoney: '0',
    rapidExitEnabled: false,
    rapidEvalStepSec: '4',
    rapidWatchdogSec: '1',
    rapidStopLossPct: '-20',
    rapidTakeProfitTriggerPct: '45',
    rapidTakeProfitStepUpPct: '25',
    rapidTakeProfitBatchPct: '15',
    rapidProtectQuotaPct: '40',
    rapidTailSellPctOfRemaining: '15',
    rapidTakeProfitFloorPct: '5',
    signalSources: ['new_pool', 'near_complete', 'complete', 'token_update'],
    platforms: ['fourmeme', 'fourmeme_agent', 'xmode', 'xmode_agent'],
    autoTaskFromWsEnabled: true,
    autoTaskAthMcapUsd: '10000',
    autoTaskPlatforms: ['fourmeme', 'fourmeme_agent'],
    autoTaskMaxPerSignal: '5',
    autoTaskMinMarketCapUsd: '',
    autoTaskMaxMarketCapUsd: '',
    autoTaskMinTokenAgeSeconds: '',
    autoTaskMaxTokenAgeSeconds: '',
    autoTaskMinHolders: '',
    autoTaskMaxHolders: '',
    autoTaskMinKol: '',
    autoTaskMaxKol: '',
    xmodeTasks: [],
  },
  tokenSnipe: {
    enabled: true,
    targetUsers: [],
    playSound: true,
    soundPreset: 'Boom',
    tasks: [],
  },
};

const DEFAULT_ADVANCED_AUTO_SELL: AdvancedAutoSellConfig = {
  enabled: false,
  rules: [
    { id: 'tp_100', type: 'take_profit', triggerPercent: 100, sellPercent: 50 },
    { id: 'tp_300', type: 'take_profit', triggerPercent: 300, sellPercent: 50 },
    { id: 'sl_50', type: 'stop_loss', triggerPercent: -50, sellPercent: 100 },
  ],
  trailingStop: {
    enabled: false,
    mode: 'trailing_stop',
    callbackPercent: 20,
    sellPercent: 80,
    rollingSellPercent: 15,
    rollingStepPercent: 25,
    rollingFloorPercent: 15,
    activationMode: 'after_first_take_profit',
  },
};

export const AUTO_LOCK_SECONDS_MIN = 30;
export const AUTO_LOCK_SECONDS_MAX = 3600;

export function defaultSettings(): Settings {
  return {
    chainId: ChainId.BNB,
    chains: {
      [ChainId.ETH]: ETH_MAINNET,
      [ChainId.BNB]: BSC_MAINNET,
      [ChainId.HYPER]: HYPER_MAINNET,
      [ChainId.RH]: RH_MAINNET,
      [ChainId.SOL]: SOL_MAINNET,
    },
    autoLockSeconds: 30 * 60, // 30 minutes
    selectedTradeWallets: [],
    multiWalletBuyMode: 'uniform',
    childWalletBuyAmountsBnb: {},
    childWalletBuyPresetAmountsNative: {},
    locale: 'zh_CN',
    accountAliases: {},
    toastPosition: 'top-center',
    seedreamApiKey: '',
    bloxrouteAuthHeader: '',
    quickBuy1Bnb: '0',
    quickBuy2Bnb: '0',
    keyboardShortcutsEnabled: false,
    tradeSuccessSoundEnabled: false,
    tradeSuccessSoundPresetBuy: 'Bell',
    tradeSuccessSoundPresetSell: 'Coins',
    tradeSuccessSoundVolume: 60,
    limitOrderScanIntervalMs: 3000,
    tokenBalancePollIntervalMs: 2000,
    ui: {
      showToolbar: true,
      limitTradePanelOnlyOnTokenPage: false,
      gmgnLimitOrderPriceEnabled: false,
      quickBuyEnabled: false,
      quickCookingEnabled: false,
      newPoolMonitorEnabled: false,
      newCoinSniperEnabled: false,
      consoleLogsEnabled: false,
    },
    telegram: {
      enabled: false,
      botToken: '',
      chatId: '',
      userId: '',
      enforceUserId: false,
      chainId: 56,
      pollIntervalMs: 2000,
      notifyTradeSubmitted: true,
      notifyTradeSuccess: true,
      notifyTradeRetrying: true,
      notifyLimitOrder: true,
      notifyQuickTrade: true,
    },
    autoTrade: DEFAULT_AUTOTRADE,
    advancedAutoSell: DEFAULT_ADVANCED_AUTO_SELL,
  };
}
